# Generated by Django 6.0.1 on 2026-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(choices=[('socialengi', "usurpation d'identité"), ('escroquerie', 'fraude en ligne'), ('chantage', 'Cyber harcèlement'), ('phishing', 'Hameçonnage'), ('malware', 'Logiciel malveillant'), ('hacking', 'Piratage de compte')], max_length=50)),
                ('description', models.TextField()),
                ('email_contact', models.EmailField(max_length=254)),
                ('capture_ecran', models.ImageField(blank=True, null=True, upload_to='incidents/%Y/%m/')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
        ),
    ]
