# Generated by Django 6.0.1 on 2026-02-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberHygiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('categorie', models.CharField(choices=[('deepfake', 'Deepfake'), ('ranconware', 'Rançonware'), ('phishing', 'Phishing'), ('fake-news', 'Fake News'), ('autre', 'Autre')], max_length=50)),
                ('image', models.ImageField(upload_to='cyber_hygiene/')),
                ('description', models.TextField(max_length=500)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conseil Cyber',
                'verbose_name_plural': 'Conseils Cyber',
                'ordering': ['-date_pub'],
            },
        ),
    ]
