# Generated by Django 6.0.1 on 2026-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cybersens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberhygiene',
            name='categorie',
            field=models.CharField(choices=[('deepfake', 'Deepfake'), ('ranconware', 'Ransonware'), ('phishing', 'Phishing'), ('fake-news', 'Fake News'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cyberhygiene',
            name='description',
            field=models.TextField(max_length=700),
        ),
    ]
